status: 1
pattern: 'Agreement for document  [node:field_ais_document:entity:nid]'
escape: false
preserve_titles: false
save: true
chunk: 50
dependencies:
  config:
    - node.type.ais_agreement
new_content_behavior: 0
