status: 1
pattern: 'Subject Analysis for [node:field_ais_document:entity:nid] (assignment [node:field_ais_assignment:entity:nid])'
escape: false
preserve_titles: false
save: true
chunk: 50
dependencies:
  config:
    - node.type.ais_subject_analysis
new_content_behavior: 0
